---

- group: name=admin state=present

- name: Create admin users
  action: user name={{ user_name }} groups=admin,adm shell=/bin/bash password={{ user_password }} comment="Superhero"

- name: Install authorized keys
  authorized_key: user={{ user_name }} key="{{ item }}" state=present
  with_items: user_public_keys


- name: ensure sudoers.d is enabled
  lineinfile: dest=/etc/sudoers state=present backup=yes regexp="^#includedir /etc/sudoers.d" line="#includedir /etc/sudoers.d"

- name: ensure the user can execute sudo commands without a password
  copy: content="%{{ user_name }} ALL=(ALL) NOPASSWD:ALL" dest=/etc/sudoers.d/{{ user_name }} owner=root group=root mode=0440